language: node_js
node_js: 
  - '12'

services:
  - docker

before-install: 
  script: docker_bash_before
  - docker-compose -f docker-compose.yaml up --build --no-start
deploy:
  provider: script
  script: bash docker_bash
  on:
    branch: master
