language: node_js
node_js: 
  - '12'

services:
  - docker

before-install: 
  - docker rmi --force registry.heroku.com/shreesharaj/katte:frontend registry.heroku.com/shreesharaj/katte:backend registry.heroku.com/shreesharaj/katte:prod 
  - docker-compose -f docker-compose.yaml up --build --no-start
deploy:
  provider: script
  script: bash docker_bash
  on:
    branch: master
