language: node_js
node_js: 
  - '12'
services:
  - docker

deploy:
  provider: heroku
  api_key: 2fc8009c-0ce5-44bf-b6f7-2cc0c13912d4
  app: katte-game
  script: docker-compose -f docker-compose.yaml up --build