language: node_js
node_js: 
  - '12'

services:
  - docker

image: shreesharaj/katte:prod
build: 
  - docker-compose -f docker-compose.yaml -p shreesharaj/katte:prod up --build
deploy:
  provider: script
  script: bash docker_bash
  on:
    branch: master
