language: node_js
node_js: 
  - '12'
before_install: 
  - docker-compose -f docker-compose.yaml -p shreesharaj/katte --build
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
