
version: "3.3"

services:
  backend:
    build:
      context: .
      dockerfile: DockerfileServer
    #We use proxy, so we don't want to access the backend on port 9000, just on 8000
    #ports:
    #  - "9000:9000"
    restart: unless-stopped
    volumes:
      - ./node_modules:/app/node_modules
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    restart: unless-stopped
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./client/node_modules:/app/node_modules
      - .:/app
  proxy:
    image: nginx:1.17
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf